version: "3"
services:
  webapi:
    container_name: fastify-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/share/app
    volumes:
      - ${PWD}/credentials:/usr/share/app/credentials/
    ports:
      - 127.0.0.1:8989:80
    links:
      - "database"
    entrypoint: ./wait-for-it.ash -h database.deploy -p 5432 -- npm run prod

  database:
    container_name: fastify-db
    hostname: database.deploy
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fastify
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin:
    container_name: fastify-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: divertiti@feddynventor.ddns.net
      PGADMIN_DEFAULT_PASSWORD: cicciopasticcio
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:
